name: screenshots3
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 3.0.0
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  process: ^4.0.0

dev_dependencies:
  pedantic: any

executables:
  screenshots: main