name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.1.1
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^1.6.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.6.2
  process: ^4.0.0

dev_dependencies:
  mockito: ^5.0.3
  pedantic: ^1.8.0+1
  quiver: ^3.0.0

executables:
  screenshots: main