name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.1.1
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^1.6.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.6.2
  file: ^6.0.0
  archive: ^3.1.2
  platform: ^3.0.0
  process: ^4.0.0
  meta: ^1.1.6
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.8
  test_api: ^0.3.0
  mockito: ^5.0.3
  pedantic: ^1.8.0+1
  quiver: ^3.0.0
  collection: any

executables:
  screenshots: main